### PR TITLE
fix: fix a compilation error on clang

### PR DESCRIPTION
**Pull request by zhangyifan27**
Fix a compilation error: https://github.com/XiaoMi/rdsn/runs/2786707126?check_suite_focus=true, which was introduced by https://github.com/XiaoMi/rdsn/pull/834

### CODE REVIEW

**Review by levy5307 — APPROVED** [review]

**Comment by Shuo-Jia** [comment]
> which is introduced by #834

Why this pr passed?

**Review by Shuo-Jia — APPROVED** [review]
